name: Setup
description: "Setup repository"
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        cache: true
    - uses: actions/setup-node@v6
      with:
        version: 22
        cache: "pnpm"
    - run: pnpm ci
      shell: bash
